### ISSUE TITLE
R.eqProps would be awesome

### ISSUE THREAD

**Issue by anotheredward** [mediasuitenz/ramda-extended#1]
http://ramdajs.com/docs/#eqProps

Would allow:

``` javascript
R.eqProps('id', user1, user2) // => true
```

Instead of:

``` javascript
user1.get('id') === user2.get('id') // => true
```

**Comment by pnw** [comment]
@anotheredward See: https://github.com/mediasuitenz/ember-cli-ramda-extended/blob/master/vendor/ramda-ember.js#L51

Any ember-related functionality is implemented in that file.
